stages:
  - build

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker info
  script:
    - 'echo "Building Docker image..."'
    - 'docker build -t test:1.0 .'
    - 'echo "Docker image built successfully"'
    - 'docker run test:1.0'